### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by theUniC** [nrk/phpiredis#29]
Hi,

I have created a PR on the Homebrew's PHP repository (https://github.com/Homebrew/homebrew-php/pull/1312).

The only requirement is to tag a release for the Homebrew Formula to not to point to the HEAD of the extension.

Can you tag a release?

Thanks in advance!
Christian.

**Comment by mbadolato** [comment]
@theUniC Looks like hiredis had a few releases this year. Can this be tagged so that the Homebrew/homebrew-php#1312 can be reopened and we can hopefully get the brew formula added?

**Comment by nrk** [comment]
Predis v1.0.0 is finally going to be tagged as soon as the `php7` branch gets merged into master (see #50 for details). Thanks for the patience!

**Comment by DavidGarciaCat** [comment]
Have you considered to build a `deb` and/or `rpm` files, to be provided by OS distributions via package repositories?

**Comment by nrk** [comment]
@DavidGarciaCat we could provide spec files for creating those packages (we already have #16 pending that covers RPM) but I'd prefer contributions from someone that has some experience with packaging for various distributions. I'd also love to have phpiredis available on PECL, see #44.

**Comment by DavidGarciaCat** [comment]
@nrk I understand and I agree 👍 anyway, I have just installed the PHP7 branch, so I am going to run some tests. Thanks for the update!

**Comment by remicollet** [comment]
@nrk about RPM, as soon as an official release will exists (and preferably a PECL release), I will publish RPM on my [repository ](https://blog.remirepo.net/pages/PECL-extensions-RPM-status) with some other extensions, and will submit it for review for official Fedora/EPEL repository.

**Comment by remicollet** [comment]
@nrk, package build for my [repository](https://blog.remirepo.net/pages/PECL-extensions-RPM-status#c6495) from current master.

RPM available for Fedora 22-25, RHEL / CentOS 6-7, i386, x86_64, NTS, ZTS, for PHP 5.4; 5.5; 5.6, 7.0 and 7.1 (all build ok, including test suite).

**Comment by nrk** [comment]
I guess that after @remicollet's latest contributions there's really no need to further postpone a v1.0.0 release, plan to push the tag in a week at max. As for PECL we'll see how it goes after introducing phpiredis on the pecl-devel mailing list, as suggested on #44.

**Comment by nrk** [comment]
I can finally close this issue since I've just tagged v1.0.0 as the first stable release of phpiredis! :tada: The default branch of the repository is now `v1.0`, the `master` branch is going to be reserved to the development of the next major version. In the coming weeks I will try to make the library available on PECL and I hope to get some help with packaging for various distributions (@remicollet :+1:). Thanks everyone for the patience till now! :smiley:

**Comment by remicollet** [comment]
> I hope to get some help with packaging for various distributions 

At least RPM are already available in my repository for
- Fedora 22 to 25
- RHEL / CentOS 5 to 7
- PHP 5.4, 5.5, 5.6, 7.0 and 7.1
- base and SCL (parallel installation) packages

;)

https://blog.remirepo.net/pages/PECL-extensions-RPM-status#c6514

Next step: review for official repository.

**Comment by remicollet** [comment]
@nrk for your information : https://bugzilla.redhat.com/1398799 (Review for official repository)

Target will be Fedora 24+ and EPEL-7 (for RHEL / CentOS 7)
