### ISSUE TITLE
Problem with different installation path of Redis and Hiredis on Webuzo

### ISSUE THREAD

**Issue by stonecold123** [nrk/phpiredis#35]
Hi,
I'm using Webuzo on Centos. The php path is `/usr/local/apps/php54/bin/php` and Hiredis is in `/usr/local/hiredis/`. The script wasn't able to find hiredis installation. I tried 
 `/usr/local/apps/php54/bin/phpize && ./configure --enable-phpiredis --with-hiredis-dir=/usr/local --with-php-config=/usr/local/apps/php54/bin/php-config`  

but it's still showing `checking for hiredis installation... configure: error: not found`

Here's the log:
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
......................
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/apps/php54
checking for PHP includes... -I/usr/local/apps/php54/include/php -I/usr/local/apps/php54/include/php/main -I/usr/local/apps/php54/include/php/TSRM -I/usr/local/apps/php54/include/php/Zend -I/usr/local/apps/php54/include/php/ext -I/usr/local/apps/php54/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/apps/php54/lib/extensions/no-debug-non-zts-20100525
checking for PHP installed headers prefix... /usr/local/apps/php54/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable phpiredis support... yes, shared
checking for hiredis library... yes, shared
checking for hiredis installation... configure: error: not found //**************

**Comment by newms87** [comment]
How did you fix it?

**Comment by ssi-anik** [comment]
> How did you fix it?

```

RUN apt-get install -y wget libhiredis-dev
RUN wget https://github.com/nrk/phpiredis/archive/v1.0.0.zip \
    && ( \
        unzip v1.0.0.zip \
        && cd phpiredis-1.0.0 \
        && phpize \
        && ./configure --enable-phpiredis --with-hiredis-dir \
        && make \
        && make install \
    ) \
    && rm -r phpiredis-1.0.0

RUN docker-php-ext-enable phpiredis
```

Mine looks like this. I was trying docker. so if you're trying to install in your pc, you just try the commands without `RUN`.
