### ISSUE TITLE
make compile error

### ISSUE THREAD

**Issue by Barbery** [nrk/phpiredis#45]
phpiredis.c:36:32: error: unknown type name ‘zend_rsrc_list_entry’

php -v
PHP 7.0.3-13+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.9.2, https://blackfire.io, by Blackfireio Inc.

**Comment by abnud1** [comment]
I have the same problem, hmmm could be a compatibility issue with php7

**Comment by nrk** [comment]
I'm closing this issue related to PHP 7 builds, see #50 for details.
