### ISSUE TITLE
PHP: Unable to load dynamic library

### ISSUE THREAD

**Issue by tndhl** [nrk/phpiredis#46]
I have compiled phpiredis with following commands:

`git clone https://github.com/nrk/phpiredis.git`
`cd phpiredis`
`phpize && ./configure --enable-phpiredis`
`make && make install`

And included library as follows: `echo extension=/usr/lib64/php/5.5/modules/phpiredis.so > /etc/php.d/redis.ini`

But I got this error:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/5.5/modules/phpiredis.so' - /usr/lib64/php/5.5/modules/phpiredis.so: undefined symbol: redisReplyReaderGetError in Unknown on line 0`

Could any one help?

**Comment by nickpastuhov** [comment]
`redisReplyReaderGetError` support removed in version 1.0.0: https://github.com/redis/hiredis/blob/master/CHANGELOG.md

**Comment by jbbrunsveld** [comment]
Pull request  #47 should fix this issue.

**Comment by nrk** [comment]
Please note that hiredis v1.0.0 is a work-in-progress and it's still unreleased so you should stick with hiredis v0.13 for now. For this reason I removed the `bug` label, I'll decide how to handle the transition in a few days after merging the `php7` branch.

**Comment by icywind** [comment]
I see the same problem here, even after I reverted to v0.13.  Is there a commit I should revert phpiredis to?

**Comment by palmic** [comment]
Will somebody finally fix this issue??

**Comment by devrck** [comment]
@nrk any follow up?

**Comment by fridzema** [comment]
Same error in 2019:
php: symbol lookup error: /usr/lib/php/20180731/phpiredis.so: undefined symbol: redisReplyReaderCreate

Is this package still under development @nrk?

**Comment by devrck** [comment]
@fridzema you need to use a [hiredis v0.13](https://github.com/redis/hiredis/tree/v0.13.3)

**Comment by yanzzchn** [comment]
'Note': Installing the phpiredis extension requires php to install both the APC and APCU extensions in addition to Hiredis, otherwise the dynamic library cannot be loaded.

**Comment by nrk** [comment]
Chenges to support Hiredis >= 0.14, >= 1.0 have been merged in the `v1.1` branch, the new minor release will be shipped in a few days is everything is fine. Thank you.
