### ISSUE TITLE
phpiredis for snc_redis

### ISSUE THREAD

**Issue by zaiddabaeen** [nrk/phpiredis#56]
Has anyone got this working for snc_redis for symfony 2/3?

**Comment by nrk** [comment]
I don't see why you shouldn't be able to use phpiredis since it's completely wrapped by Predis but I guess this question should be asked on [snc/SncRedisBundle](https://github.com/snc/SncRedisBundle) anyway.

**Comment by zaiddabaeen** [comment]
Solution:
https://github.com/snc/SncRedisBundle/issues/221
