### ISSUE TITLE
Failed make tests

### ISSUE THREAD

**Issue by bitmammoth** [nrk/phpiredis#58]

**Comment by bitmammoth** [comment]
I see this was an old issue and version of this library apparently sorry :)

**Comment by bitmammoth** [comment]
I closed this originally as I thought it had been caused by an old version of this lib but it seems this is different. 

phpiredis | enabled
-- | --
phpiredis version | 1.0.0
hiredis version | 0.13.3

 make test

Build complete.
Don't forget to run 'make test'.


                                                                     
PHP         : /usr/bin/php7.2 
PHP_SAPI    : cli
PHP_VERSION : 7.2.9-1+ubuntu18.04.1+deb.sury.org+1
ZEND_VERSION: 3.2.0
PHP_OS      : Linux - Linux  -Q1 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
INI actual  :  /phpiredis/tmp-php.ini
More .INIs  :   
---------------------------------------------------------------------
PHP         : /usr/bin/phpdbg7.2 
PHP_SAPI    : phpdbg
PHP_VERSION : 7.2.9-1+ubuntu18.04.1+deb.sury.org+1
ZEND_VERSION: 3.2.0
PHP_OS      : Linux - Linux  -Q1 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
INI actual  :  /phpiredis/tmp-php.ini
More .INIs  : 
---------------------------------------------------------------------
CWD         :  /phpiredis
Extra dirs  : 
VALGRIND    : Not used
                                                                     
TIME START 2018-09-13 10:34:53
                                                                     
PASS [CLIENT] Connect to Redis [tests/client_001.phpt] 
PASS [CLIENT] Persistent and non-persistent connections [tests/client_002.phpt] 
SKIP [CLIENT] Persistent and non-persistent connections (UNIX socket) [tests/client_003.phpt] reason: Cannot find UNIX domain socket file at /tmp/redis.sock
PASS [CLIENT] Execute commands [tests/client_004.phpt] 
PASS [CLIENT] Execute pipelined commands [tests/client_005.phpt] 
PASS [CLIENT] Execute pipelined commands returning nested multibulk responses [tests/client_006.phpt] 
PASS [CLIENT] Execute commands (binary-safe) [tests/client_007.phpt] 
PASS [CLIENT] Execute commands with binary data (binary-safe) [tests/client_008.phpt] 
PASS [CLIENT] Execute pipelined commands (binary safe) [tests/client_009.phpt] 
PASS [CLIENT] Do not attempt to reconnect upon disconnection [tests/client_010.phpt] 
PASS [CLIENT] Do not attempt to reconnect upon disconnection (pipeline) [tests/client_011.phpt] 
FAIL [READER] Create reader resource [tests/reader_001.phpt] 
FAIL [READER] Feed reader and parse responses [tests/reader_002.phpt] 
FAIL [READER] Check reader state [tests/reader_003.phpt] 
FAIL [READER] Reset reader [tests/reader_004.phpt] 
FAIL [READER] Response types [tests/reader_005.phpt] 
FAIL [READER] Set custom error handler [tests/reader_006.phpt] 
FAIL [READER] Set custom status handler [tests/reader_007.phpt] 
FAIL [READER] Custom error handler throwing exceptions or returning objects [tests/reader_008.phpt] 
FAIL [READER] Properly handle NULL responses [tests/reader_009.phpt] 
FAIL [READER] Keep multibulk responses types [tests/reader_010.phpt] 
FAIL [READER] Test regression for segfaults [tests/reader_011.phpt] 
PASS [READER] Parameters formatting should not modify input argument. [tests/reader_012.phpt] 
PASS [READER] Parameters formatting should not break on many arguments [tests/reader_013.phpt] 
PASS [SERIALIZER] Command serialization [tests/serializer_001.phpt] 
PASS [SERIALIZER] Command serialization with non-string arguments [tests/serializer_002.phpt] 
PASS [UTILS] Calculate the CRC16 of strings [tests/utils_001.phpt] 
                                                                     
TIME END 2018-09-13 10:34:55

                                                                     
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   15
---------------------------------------------------------------------

Number of tests :   27                26
Tests skipped   :    1 (  3.7%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   11 ( 40.7%) ( 42.3%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   15 ( 55.6%) ( 57.7%)
---------------------------------------------------------------------
Time taken      :    2 seconds
                                                                     

                                                                     
FAILED TEST SUMMARY
---------------------------------------------------------------------
[READER] Create reader resource [tests/reader_001.phpt]
[READER] Feed reader and parse responses [tests/reader_002.phpt]
[READER] Check reader state [tests/reader_003.phpt]
[READER] Reset reader [tests/reader_004.phpt]
[READER] Response types [tests/reader_005.phpt]
[READER] Set custom error handler [tests/reader_006.phpt]
[READER] Set custom status handler [tests/reader_007.phpt]
[READER] Custom error handler throwing exceptions or returning objects [tests/reader_008.phpt]
[READER] Properly handle NULL responses [tests/reader_009.phpt]
[READER] Keep multibulk responses types [tests/reader_010.phpt]
[READER] Test regression for segfaults [tests/reader_011.phpt]

**Comment by bitmammoth** [comment]
php: symbol lookup error: /usr/lib/php/20170718/phpiredis.so: undefined symbol: redisReplyReaderCreate

Does this still happen with this version? I'm confused here :)

**Comment by yanzzchn** [comment]
'Note': Installing the phpiredis extension requires php to install both the APC and APCU extensions in addition to Hiredis, otherwise the dynamic library cannot be loaded.

**Comment by nrk** [comment]
Changes to support Hiredis >= 0.14, >= 1.0 have been merged in the `v1.1` branch, the new minor release will be shipped in a few days is everything is fine. Thank you.
