### ISSUE TITLE
undefined symbol: redisReplyReaderGetReply in Unknown on line 0

### ISSUE THREAD

**Issue by yanzzchn** [nrk/phpiredis#61]
[root@localhost ~/phpiredis]#make test

Build complete.
Don't forget to run 'make test'.

PHP Warning:  PHP Startup: Unable to load dynamic library '/root/phpiredis/modules/phpiredis.so' - /root/phpiredis/modules/phpiredis.so: undefined symbol: redisReplyReaderGetReply in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/phpiredis/modules/phpiredis.so' - /root/phpiredis/modules/phpiredis.so: undefined symbol: redisReplyReaderGetReply in Unknown on line 0

=====================================================================
PHP         : /usr/bin/php
Warning: PHP Startup: Unable to load dynamic library '/root/phpiredis/modules/phpiredis.so' - /root/phpiredis/modules/phpiredis.so: undefined symbol: redisReplyReaderGetReply in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 5.6.40
ZEND_VERSION: 2.6.0
PHP_OS      : Linux - Linux localhost.localdomain 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 14:52:26 UTC 2019 x86_64
INI actual  : /root/phpiredis/tmp-php.ini
More .INIs  :
CWD         : /root/phpiredis
Extra dirs  :
VALGRIND    : Not used

[root@localhost /data/wwwroot/code/_example/app]#php index.php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/phpiredis.so' - /usr/lib64/php/modules/phpiredis.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Call to undefined function phpiredis_connect() in /data/wwwroot/code/library/includes/class/memcachedb.php on line 75

**Comment by yanzzchn** [comment]
'Note': Installing the phpiredis extension requires php to install both the APC and APCU extensions in addition to Hiredis, otherwise the dynamic library cannot be loaded.

**Comment by gearhead** [comment]
@yanzzchn This is not my experience. I use it on armv6 and armv7 and do not have to install/load php-apcu extension to get this to run/work.

**Comment by gearhead** [comment]
I get the same error when I build it for armv7h, but not on armv6h. On armv6h, I build it and everything works. This is without adding php-acpu and enabling acp and acpu. I have never used these in my project (5 years) and never needed them to work with redis/hiredis in my project. I have not tried this with x86, so I do not know how it works on a PC, only Raspberry Pis.  See my other issue
[https://github.com/nrk/phpiredis/issues/63](https://github.com/nrk/phpiredis/issues/63)

**Comment by nrk** [comment]
Changes to support Hiredis >= 0.14, >= 1.0 have been merged in the `v1.1` branch, the new minor release will be shipped in a few days is everything is fine. Thank you.
