### ISSUE TITLE
Will recent Hiredis upgrades be implemented?

### ISSUE THREAD

**Issue by gearhead** [nrk/phpiredis#64]
Hiredis recently went to 0.14.1 and is working towards a 1.0.0 release with some breaking changes. With 0.14 be implemented? 1.0.0?

**Comment by gearhead** [comment]
I posted a pull request. This pull request works with hiredis 0.14. Confirmed on x64, armv6h, armv7h

**Comment by Approach** [comment]
1.0 is out now, could that be why I keep getting 

checking for hiredis library... yes, shared
checking for hiredis installation... configure: error: not found

even after supplying the directory of hiredis.0.so ?

**Comment by gearhead** [comment]
Which distro are using that is at 1.0? I am on Arch and we are still at hiredis 0.14. I have not looked at 1.0 to see what will be required only that the hiredis page mentions changes which will break stuff...

**Comment by Approach** [comment]
Seems I misread the repo readme, my mistake.
I'm not on 1.0, I am apparently on 0.12.1 on CentOS 7. installed via yum

**Comment by nrk** [comment]
Issues with newer hiredis versions will be addressed in the next few days 👍

**Comment by nrk** [comment]
Changes to support Hiredis >= 0.14, >= 1.0 have been merged in the `v1.1` branch, the new minor release will be shipped in a few days is everything is fine. `v1.0` will remain stuck to older Hiredis versions. Thank you.

**Comment by gearhead** [comment]
Thank you! Built. works!

**Comment by nrk** [comment]
Great, thanks.
