### ISSUE TITLE
PHP unable to load phpiredis.so

### ISSUE THREAD

**Issue by socket0** [nrk/phpiredis#7]
I cannot load the phpiredis module, as it fails to find libhiredis.so.0.10:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20090626/phpiredis.so' - libhiredis.so.0.10: cannot open shared object file: No such file or directory in Unknown on line 0
```

However, libhiredis.so.0.10 is built and located here:

/usr/local/lib/libhiredis.so.0.10

I built phpiredis with the hiredis location specified here:

./configure --enable-phpiredis --with-hiredis-dir=/usr/local/lib

Is this phpiredis failing, or hiredis?

**Comment by blacklizard** [comment]
If anyone have this problem, this is how i fixed in my ubuntu installation. (php-fpm)

Just follow the step from readme

```
git clone https://github.com/nrk/phpiredis.git
cd phpiredis
phpize && ./configure --enable-phpiredis
make && make install
```

Then in `/etc/php5/mods-available` create a file called `phpiredis.ini`. Add the content below to that .ini
```
; configuration for phpiredis  module
extension=phpiredis.so
```

Then 

```
sudo php5enmod phpiredis
```

Restart your php and websever, should be fine

**Comment by tdn1234** [comment]
Thanks in advanced @blacklizard , you saved my day.
